# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ddb55aa76bcf71fa3f0d260816083a86c19c67c6a2bcbb9e0f963bd2d243f4b1a6dcae616e1bce3d1eeeee7061c0f75e78a811121f7f2ea92702cfaa0bc9436

test:
  secret_key_base: 9fef4caa23c06086194c1a86566f2b370e99dbd2329ebe2f3126ea927e6b2036e6abb419c1886a3b61915955c8ff716a9f7ebd8a18ad7bddbcf0426e3da56740

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
