# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39f2c256ad642b184f56d79646fbea510f64f499c7ef428d6217fe318e32ac93ce80e2f46214b12ee7e84b7af4405d48cc04ae8954e55d8b4b9de12404085406

test:
  secret_key_base: 26dbac9b40d1c150b2375f5e289f2513cce1d035dec9bdfc800ea710d29c1947a9ed5d273a6f7d0fc237cd3595e8f5f7aa2ee3ae8299d40f1c2265a55cc7ebda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
